stages:
- docs

pages:
  image: "iquiw/alpine-emacs:latest"
  stage: docs
  before_script:
  - mkdir -p public
  script:
  - emacs --batch --no-init-file --load "publish.el" --funcall "live-wc-publish--all"
  - cp doc/live-wc-tooltip-demo.png public/live-wc-tooltip-demo.png
  - cp doc/live-wc.html public/index.html
  artifacts:
    paths:
    - public
  only:
    refs:
    - master
